# coding: utf-8

"""
    CyborgDB Service

    REST API for CyborgDB: The Confidential Vector Database

    The version of the OpenAPI document: 0.14.1.dev95
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cyborgdb.openapi_client.models.binary_vector_batch_contents_inner import BinaryVectorBatchContentsInner
from typing import Optional, Set
from typing_extensions import Self

class BinaryVectorBatch(BaseModel):
    """
    Represents a batch of vectors in binary format for efficient transfer.  Attributes:     ids (List[str]): List of unique identifiers for each vector.     vectors_b64 (str): Base64-encoded float32 numpy array (shape: n_vectors x dimension).     dimension (int): The dimension of each vector.     metadata (Optional[List[Optional[Dict[str, Any]]]]): Optional metadata for each vector.     contents (Optional[List[Optional[Union[str, bytes]]]]): Optional contents for each vector.
    """ # noqa: E501
    ids: List[StrictStr]
    vectors_b64: StrictStr
    dimension: StrictInt
    metadata: Optional[List[Optional[Dict[str, Any]]]] = None
    contents: Optional[List[Optional[BinaryVectorBatchContentsInner]]] = None
    __properties: ClassVar[List[str]] = ["ids", "vectors_b64", "dimension", "metadata", "contents"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BinaryVectorBatch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in contents (list)
        _items = []
        if self.contents:
            for _item_contents in self.contents:
                if _item_contents:
                    _items.append(_item_contents.to_dict())
            _dict['contents'] = _items
        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        # set to None if contents (nullable) is None
        # and model_fields_set contains the field
        if self.contents is None and "contents" in self.model_fields_set:
            _dict['contents'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BinaryVectorBatch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ids": obj.get("ids"),
            "vectors_b64": obj.get("vectors_b64"),
            "dimension": obj.get("dimension"),
            "metadata": obj.get("metadata"),
            "contents": [BinaryVectorBatchContentsInner.from_dict(_item) for _item in obj["contents"]] if obj.get("contents") is not None else None
        })
        return _obj


