# coding: utf-8

"""
    CyborgDB Service

    REST API for CyborgDB: The Confidential Vector Database

    The version of the OpenAPI document: 0.17.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cyborgdb.openapi_client.models.binary_query_batch import BinaryQueryBatch
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BinaryQueryRequest(BaseModel):
    """
    Request model for batch similarity search using binary format.  This is more efficient than BatchQueryRequest for large batches as vectors are sent as base64-encoded binary data instead of JSON arrays.  Inherits:     IndexOperationRequest: Includes `index_name` and `index_key`.  Attributes:     batch (BinaryQueryBatch): The batch of query vectors in binary format.     top_k (Optional[int]): Number of nearest neighbors to return for each query. Defaults to 100.     n_probes (Optional[int]): Number of lists to probe during the query. Defaults to auto.     greedy (Optional[bool]): Whether to use greedy search. Defaults to False.     rerank_mult (Optional[int]): Multiplier for stage 1 retrieval in reranking indexes. Defaults to 10.     filters (Optional[Dict[str, Any]]): JSON-like dictionary specifying metadata filters. Defaults to {}.     include (List[str]): List of additional fields to include in the response. Defaults to `[]` (only IDs are returned).
    """ # noqa: E501
    index_name: StrictStr = Field(description="ID name")
    index_key: Optional[StrictStr] = Field(default=None, description="32-byte encryption key as hex string.  Required for SDK-supplied indexes; must be omitted for KMS-backed indexes (the service resolves the KEK via the index's KMSBlob).")
    batch: BinaryQueryBatch
    top_k: Optional[StrictInt] = None
    n_probes: Optional[StrictInt] = None
    greedy: Optional[StrictBool] = None
    rerank_mult: Optional[StrictInt] = None
    filters: Optional[Dict[str, Any]] = None
    include: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["index_name", "index_key", "batch", "top_k", "n_probes", "greedy", "rerank_mult", "filters", "include"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BinaryQueryRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of batch
        if self.batch:
            _dict['batch'] = self.batch.to_dict()
        # set to None if index_key (nullable) is None
        # and model_fields_set contains the field
        if self.index_key is None and "index_key" in self.model_fields_set:
            _dict['index_key'] = None

        # set to None if top_k (nullable) is None
        # and model_fields_set contains the field
        if self.top_k is None and "top_k" in self.model_fields_set:
            _dict['top_k'] = None

        # set to None if n_probes (nullable) is None
        # and model_fields_set contains the field
        if self.n_probes is None and "n_probes" in self.model_fields_set:
            _dict['n_probes'] = None

        # set to None if greedy (nullable) is None
        # and model_fields_set contains the field
        if self.greedy is None and "greedy" in self.model_fields_set:
            _dict['greedy'] = None

        # set to None if rerank_mult (nullable) is None
        # and model_fields_set contains the field
        if self.rerank_mult is None and "rerank_mult" in self.model_fields_set:
            _dict['rerank_mult'] = None

        # set to None if filters (nullable) is None
        # and model_fields_set contains the field
        if self.filters is None and "filters" in self.model_fields_set:
            _dict['filters'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BinaryQueryRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "index_name": obj.get("index_name"),
            "index_key": obj.get("index_key"),
            "batch": BinaryQueryBatch.from_dict(obj["batch"]) if obj.get("batch") is not None else None,
            "top_k": obj.get("top_k"),
            "n_probes": obj.get("n_probes"),
            "greedy": obj.get("greedy"),
            "rerank_mult": obj.get("rerank_mult"),
            "filters": obj.get("filters"),
            "include": obj.get("include")
        })
        return _obj


