# coding: utf-8

"""
    CyborgDB Service

    REST API for CyborgDB: The Confidential Vector Database

    The version of the OpenAPI document: 0.16.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateIndexRequest(BaseModel):
    """
    Request model for creating a new encrypted DiskIVF index.  Attributes:     index_name: The name/identifier of the index.     kms_name: Optional name of a `kms.registry` entry in the service         YAML. When supplied, the service generates the DEK itself,         wraps it under that entry's KMS, and persists the envelope.         For `provider: none` entries the SDK must also supply         `index_key` — it becomes the wrapping KEK. For real KMS         entries `index_key` must be omitted; supplying both         is rejected by the service with a 400.     index_key: A 32-byte encryption key as a hex string. Required         when `kms_name` is omitted (legacy: SDK provides the DEK         directly). Also required when `kms_name` references a         `provider: none` registry entry (the KEK).     dimension (Optional[int]): Dimensionality of the vectors. Auto-detected         from the first upsert if omitted.     embedding_model (Optional[str]): Optional embedding model name.     metric (Optional[str]): Optional distance metric.     storage_precision (Optional[Literal[\"float32\", \"float16\"]]): On-disk         rerank-vector dtype. Defaults to float32 in core.
    """ # noqa: E501
    index_name: StrictStr = Field(description="ID name")
    kms_name: Optional[StrictStr] = Field(default=None, description="Name of a kms.registry entry in the service YAML. When supplied, the service wraps a fresh DEK via that KMS and persists the envelope; the SDK doesn't need to provide index_key unless the entry is provider=none.")
    index_key: Optional[StrictStr] = Field(default=None, description="32-byte encryption key as hex string. Required when kms_name is omitted, or when kms_name points at a provider=none registry entry.")
    dimension: Optional[StrictInt] = None
    embedding_model: Optional[StrictStr] = None
    metric: Optional[StrictStr] = None
    storage_precision: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["index_name", "kms_name", "index_key", "dimension", "embedding_model", "metric", "storage_precision"]

    @field_validator('storage_precision')
    def storage_precision_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['float32', 'float16']):
            raise ValueError("must be one of enum values ('float32', 'float16')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateIndexRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if kms_name (nullable) is None
        # and model_fields_set contains the field
        if self.kms_name is None and "kms_name" in self.model_fields_set:
            _dict['kms_name'] = None

        # set to None if index_key (nullable) is None
        # and model_fields_set contains the field
        if self.index_key is None and "index_key" in self.model_fields_set:
            _dict['index_key'] = None

        # set to None if dimension (nullable) is None
        # and model_fields_set contains the field
        if self.dimension is None and "dimension" in self.model_fields_set:
            _dict['dimension'] = None

        # set to None if embedding_model (nullable) is None
        # and model_fields_set contains the field
        if self.embedding_model is None and "embedding_model" in self.model_fields_set:
            _dict['embedding_model'] = None

        # set to None if metric (nullable) is None
        # and model_fields_set contains the field
        if self.metric is None and "metric" in self.model_fields_set:
            _dict['metric'] = None

        # set to None if storage_precision (nullable) is None
        # and model_fields_set contains the field
        if self.storage_precision is None and "storage_precision" in self.model_fields_set:
            _dict['storage_precision'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateIndexRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "index_name": obj.get("index_name"),
            "kms_name": obj.get("kms_name"),
            "index_key": obj.get("index_key"),
            "dimension": obj.get("dimension"),
            "embedding_model": obj.get("embedding_model"),
            "metric": obj.get("metric"),
            "storage_precision": obj.get("storage_precision")
        })
        return _obj


