# coding: utf-8

"""
    CyborgDB Service

    REST API for CyborgDB: The Confidential Vector Database

    The version of the OpenAPI document: 0.17.1.dev16
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cyborgdb.openapi_client.models.bm25_config import BM25Config
from cyborgdb.openapi_client.models.metadata_field_policy import MetadataFieldPolicy
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IndexInfoResponseModel(BaseModel):
    """
    Response model for retrieving information about an index.  Attributes:     index_name (str): The name of the index.     is_trained (bool): Indicates whether the index has been trained.     dimension (int): Dimensionality of the vectors. `0` before the         first upsert when create_index was called without an explicit         dimension (auto-detect).     metric (str): Distance metric (`euclidean`, `cosine`, or         `squared_euclidean`).     n_lists (int): Number of inverted lists in the IVF index. `1`         for untrained indexes.     metadata_schema (Dict[str, MetadataFieldPolicy]): Per-field metadata         indexing overrides recorded at create time. Empty when the         index uses the default index-everything posture.     bm25 (Optional[BM25Config]): BM25 scoring config when the index has         at least one full_text field; `None` otherwise.
    """ # noqa: E501
    index_name: StrictStr
    is_trained: StrictBool
    dimension: StrictInt
    metric: StrictStr
    n_lists: StrictInt
    metadata_schema: Optional[Dict[str, MetadataFieldPolicy]] = None
    bm25: Optional[BM25Config] = None
    __properties: ClassVar[List[str]] = ["index_name", "is_trained", "dimension", "metric", "n_lists", "metadata_schema", "bm25"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IndexInfoResponseModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in metadata_schema (dict)
        _field_dict = {}
        if self.metadata_schema:
            for _key_metadata_schema in self.metadata_schema:
                if self.metadata_schema[_key_metadata_schema]:
                    _field_dict[_key_metadata_schema] = self.metadata_schema[_key_metadata_schema].to_dict()
            _dict['metadata_schema'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of bm25
        if self.bm25:
            _dict['bm25'] = self.bm25.to_dict()
        # set to None if bm25 (nullable) is None
        # and model_fields_set contains the field
        if self.bm25 is None and "bm25" in self.model_fields_set:
            _dict['bm25'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IndexInfoResponseModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "index_name": obj.get("index_name"),
            "is_trained": obj.get("is_trained"),
            "dimension": obj.get("dimension"),
            "metric": obj.get("metric"),
            "n_lists": obj.get("n_lists"),
            "metadata_schema": dict(
                (_k, MetadataFieldPolicy.from_dict(_v))
                for _k, _v in obj["metadata_schema"].items()
            )
            if obj.get("metadata_schema") is not None
            else None,
            "bm25": BM25Config.from_dict(obj["bm25"]) if obj.get("bm25") is not None else None
        })
        return _obj


