# coding: utf-8

"""
    CyborgDB Service

    REST API for CyborgDB: The Confidential Vector Database

    The version of the OpenAPI document: 0.16.3.dev1781625678
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IndexTrainingStatusResponseModel(BaseModel):
    """
    Response model for retrieving the training status of indexes.  Attributes:     training_indexes (List[str]): List of index names currently being trained or queued.     retrain_threshold (int): The multiplier used for the retraining threshold.     currently_training (Optional[str]): Name of the index currently being trained.     queued_indexes (List[str]): List of indexes queued for training.     worker_running (bool): Whether the training worker thread is running.     worker_pid (int): Deprecated - kept for backward compatibility with SDK.     global_training (Dict[str, Any]): Deprecated - kept for backward compatibility with SDK.
    """ # noqa: E501
    training_indexes: List[StrictStr]
    retrain_threshold: StrictInt
    currently_training: Optional[StrictStr] = None
    queued_indexes: Optional[List[Optional[StrictStr]]] = None
    worker_running: Optional[StrictBool] = False
    worker_pid: Optional[StrictInt] = 0
    global_training: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["training_indexes", "retrain_threshold", "currently_training", "queued_indexes", "worker_running", "worker_pid", "global_training"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IndexTrainingStatusResponseModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if currently_training (nullable) is None
        # and model_fields_set contains the field
        if self.currently_training is None and "currently_training" in self.model_fields_set:
            _dict['currently_training'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IndexTrainingStatusResponseModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "training_indexes": obj.get("training_indexes"),
            "retrain_threshold": obj.get("retrain_threshold"),
            "currently_training": obj.get("currently_training"),
            "queued_indexes": obj.get("queued_indexes"),
            "worker_running": obj.get("worker_running") if obj.get("worker_running") is not None else False,
            "worker_pid": obj.get("worker_pid") if obj.get("worker_pid") is not None else 0,
            "global_training": obj.get("global_training")
        })
        return _obj


