# coding: utf-8

"""
    CyborgDB Service

    REST API for CyborgDB: The Confidential Vector Database

    The version of the OpenAPI document: 0.17.1.dev16
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class QueryMetadataRequest(BaseModel):
    """
    Request model for a metadata-only query (no query vector).  Inherits:     IndexOperationRequest: Includes `index_name` and `index_key`.  Attributes:     filters (Optional[Dict[str, Any]]): Metadata filters as a JSON-like         dictionary. Unlike `/query`, every leaf must be resolvable from         the metadata index — see the field description.     top_k (Optional[int]): Cap on the number of ids returned. `None`         returns every match. Applied AFTER `order_by`.     order_by (Optional[str]): Metadata field to sort the matches by         (post-filter). Unordered when omitted.     ascending (bool): Sort direction when `order_by` is set.
    """ # noqa: E501
    index_name: StrictStr = Field(description="ID name")
    index_key: Optional[StrictStr] = Field(default=None, description="32-byte encryption key as hex string.  Required for SDK-supplied indexes; must be omitted for KMS-backed indexes (the service resolves the KEK via the index's KMSBlob).")
    filters: Optional[Dict[str, Any]] = Field(default=None, description="Arbitrary JSON object stored alongside the vector. Schemaless — the index's `metadata_schema` governs how fields are indexed, not what may be stored. Nested objects are addressable by dot-path in filters (`loc.city`); dates have no native type, store them as epoch millis.")
    top_k: Optional[StrictInt] = Field(default=None, description="Cap on the number of ids returned; omit for all matches. Applied after `order_by`, so it yields the first N of the sorted result.")
    order_by: Optional[StrictStr] = Field(default=None, description="Metadata field to sort matches by, applied after filtering. Unordered when omitted. Items missing the field, or holding a non-scalar, sort last.")
    ascending: Optional[StrictBool] = Field(default=True, description="Sort direction when `order_by` is set.")
    __properties: ClassVar[List[str]] = ["index_name", "index_key", "filters", "top_k", "order_by", "ascending"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QueryMetadataRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if index_key (nullable) is None
        # and model_fields_set contains the field
        if self.index_key is None and "index_key" in self.model_fields_set:
            _dict['index_key'] = None

        # set to None if filters (nullable) is None
        # and model_fields_set contains the field
        if self.filters is None and "filters" in self.model_fields_set:
            _dict['filters'] = None

        # set to None if top_k (nullable) is None
        # and model_fields_set contains the field
        if self.top_k is None and "top_k" in self.model_fields_set:
            _dict['top_k'] = None

        # set to None if order_by (nullable) is None
        # and model_fields_set contains the field
        if self.order_by is None and "order_by" in self.model_fields_set:
            _dict['order_by'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QueryMetadataRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "index_name": obj.get("index_name"),
            "index_key": obj.get("index_key"),
            "filters": obj.get("filters"),
            "top_k": obj.get("top_k"),
            "order_by": obj.get("order_by"),
            "ascending": obj.get("ascending") if obj.get("ascending") is not None else True
        })
        return _obj


