# coding: utf-8

"""
    CyborgDB Service

    REST API for CyborgDB: The Confidential Vector Database

    The version of the OpenAPI document: 0.17.1.dev16
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class QueryRequest(BaseModel):
    """
    Request model for performing a similarity search in the encrypted index.  Inherits:     IndexOperationRequest: Includes `index_name` and `index_key`.     HybridQueryParams: `text` and the fusion knobs that turn this into a         hybrid (BM25 + vector) query. A query vector is still required         even when `text` is set.  Attributes:     query_vectors (Optional[List[float]]): The vector used for the similarity search.     query_contents (Optional[str]): Text-based content used for semantic search.     top_k (Optional[int]): Number of nearest neighbors to return for each query. Defaults to 100.     n_probes (Optional[int]): Number of lists to probe during the query. Defaults to auto.     greedy (Optional[bool]): Whether to use greedy search. Defaults to False.     rerank_mult (Optional[int]): Multiplier for stage 1 retrieval in reranking indexes. Defaults to 10.     filters (Optional[Dict[str, Any]]): Metadata filters as a JSON-like         dictionary (see `FILTERS_DESCRIPTION` for the operator set).         Defaults to {}.     include (List[str]): List of additional fields to include in the response. Defaults to `[]` (only IDs are returned).
    """ # noqa: E501
    text: Optional[StrictStr] = Field(default=None, description="Query text for a BM25 full-text leg. Requires an index with at least one full_text field. Omitted/empty leaves the query text-free.")
    text_fields: Optional[List[StrictStr]] = Field(default=None, description="full_text fields the text leg searches; omitted means all of them. Naming a non-full_text field raises.")
    text_field_weights: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, description="Per-field weights on the summed per-field BM25 scores, parallel to the searched fields. Omitted means 1.0 each.")
    require_all_terms: Optional[StrictBool] = Field(default=None, description="Require every query term to match (AND) instead of any (OR, the default).")
    alpha: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Leg blend in [0, 1]: 0 = pure BM25, 1 = pure vector; omitted means 0.5. An exact endpoint skips the dead leg's retrieval.")
    rrf_k: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="RRF rank-smoothing constant (> 0; omitted means 60). Higher rewards agreement further down each leg's list.")
    window_mult: Optional[StrictInt] = Field(default=None, description="Per-leg candidate depth as a multiple of top_k (>= 1; omitted means 3), so each leg looks deeper than the final cut.")
    index_name: StrictStr = Field(description="ID name")
    index_key: Optional[StrictStr] = Field(default=None, description="32-byte encryption key as hex string.  Required for SDK-supplied indexes; must be omitted for KMS-backed indexes (the service resolves the KEK via the index's KMSBlob).")
    query_vectors: Optional[List[Union[StrictFloat, StrictInt]]] = None
    query_contents: Optional[StrictStr] = None
    top_k: Optional[StrictInt] = None
    n_probes: Optional[StrictInt] = None
    rerank_mult: Optional[StrictInt] = None
    greedy: Optional[StrictBool] = None
    filters: Optional[Dict[str, Any]] = Field(default=None, description="Metadata filters as a JSON object. Operators: `$eq`, `$ne`, `$in`, `$nin`, `$exists`, `$gt`, `$gte`, `$lt`, `$lte`, `$regex`, `$contains`, combined with `$and` / `$or` / `$nor` / `$not`. Filtering works on any metadata field; the index's `metadata_schema` only decides how a filter is resolved — fields marked `filterable` (the default) are answered from the inverted index, and `$regex` / `$contains` are answered from the regex dictionary on `pattern` fields. Anything else falls back to a post-filter over the decrypted metadata, which is correct but slower. Dates have no native type: store and filter them as epoch milliseconds.")
    include: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["text", "text_fields", "text_field_weights", "require_all_terms", "alpha", "rrf_k", "window_mult", "index_name", "index_key", "query_vectors", "query_contents", "top_k", "n_probes", "rerank_mult", "greedy", "filters", "include"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QueryRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if text (nullable) is None
        # and model_fields_set contains the field
        if self.text is None and "text" in self.model_fields_set:
            _dict['text'] = None

        # set to None if text_fields (nullable) is None
        # and model_fields_set contains the field
        if self.text_fields is None and "text_fields" in self.model_fields_set:
            _dict['text_fields'] = None

        # set to None if text_field_weights (nullable) is None
        # and model_fields_set contains the field
        if self.text_field_weights is None and "text_field_weights" in self.model_fields_set:
            _dict['text_field_weights'] = None

        # set to None if require_all_terms (nullable) is None
        # and model_fields_set contains the field
        if self.require_all_terms is None and "require_all_terms" in self.model_fields_set:
            _dict['require_all_terms'] = None

        # set to None if alpha (nullable) is None
        # and model_fields_set contains the field
        if self.alpha is None and "alpha" in self.model_fields_set:
            _dict['alpha'] = None

        # set to None if rrf_k (nullable) is None
        # and model_fields_set contains the field
        if self.rrf_k is None and "rrf_k" in self.model_fields_set:
            _dict['rrf_k'] = None

        # set to None if window_mult (nullable) is None
        # and model_fields_set contains the field
        if self.window_mult is None and "window_mult" in self.model_fields_set:
            _dict['window_mult'] = None

        # set to None if index_key (nullable) is None
        # and model_fields_set contains the field
        if self.index_key is None and "index_key" in self.model_fields_set:
            _dict['index_key'] = None

        # set to None if query_vectors (nullable) is None
        # and model_fields_set contains the field
        if self.query_vectors is None and "query_vectors" in self.model_fields_set:
            _dict['query_vectors'] = None

        # set to None if query_contents (nullable) is None
        # and model_fields_set contains the field
        if self.query_contents is None and "query_contents" in self.model_fields_set:
            _dict['query_contents'] = None

        # set to None if top_k (nullable) is None
        # and model_fields_set contains the field
        if self.top_k is None and "top_k" in self.model_fields_set:
            _dict['top_k'] = None

        # set to None if n_probes (nullable) is None
        # and model_fields_set contains the field
        if self.n_probes is None and "n_probes" in self.model_fields_set:
            _dict['n_probes'] = None

        # set to None if rerank_mult (nullable) is None
        # and model_fields_set contains the field
        if self.rerank_mult is None and "rerank_mult" in self.model_fields_set:
            _dict['rerank_mult'] = None

        # set to None if greedy (nullable) is None
        # and model_fields_set contains the field
        if self.greedy is None and "greedy" in self.model_fields_set:
            _dict['greedy'] = None

        # set to None if filters (nullable) is None
        # and model_fields_set contains the field
        if self.filters is None and "filters" in self.model_fields_set:
            _dict['filters'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QueryRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "text": obj.get("text"),
            "text_fields": obj.get("text_fields"),
            "text_field_weights": obj.get("text_field_weights"),
            "require_all_terms": obj.get("require_all_terms"),
            "alpha": obj.get("alpha"),
            "rrf_k": obj.get("rrf_k"),
            "window_mult": obj.get("window_mult"),
            "index_name": obj.get("index_name"),
            "index_key": obj.get("index_key"),
            "query_vectors": obj.get("query_vectors"),
            "query_contents": obj.get("query_contents"),
            "top_k": obj.get("top_k"),
            "n_probes": obj.get("n_probes"),
            "rerank_mult": obj.get("rerank_mult"),
            "greedy": obj.get("greedy"),
            "filters": obj.get("filters"),
            "include": obj.get("include")
        })
        return _obj


