# coding: utf-8

"""
    CyborgDB Service

    REST API for CyborgDB: The Confidential Vector Database

    The version of the OpenAPI document: 0.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cyborgdb.openapi_client.models.list_ids_request import ListIDsRequest

class TestListIDsRequest(unittest.TestCase):
    """ListIDsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListIDsRequest:
        """Test ListIDsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListIDsRequest`
        """
        model = ListIDsRequest()
        if include_optional:
            return ListIDsRequest(
                index_key = '',
                index_name = ''
            )
        else:
            return ListIDsRequest(
                index_key = '',
                index_name = '',
        )
        """

    def testListIDsRequest(self):
        """Test ListIDsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
