# coding: utf-8

"""
    CyborgDB Service

    REST API for CyborgDB: The Confidential Vector Database

    The version of the OpenAPI document: 0.12.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cyborgdb.openapi_client.models.index_training_status_response_model import IndexTrainingStatusResponseModel

class TestIndexTrainingStatusResponseModel(unittest.TestCase):
    """IndexTrainingStatusResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IndexTrainingStatusResponseModel:
        """Test IndexTrainingStatusResponseModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IndexTrainingStatusResponseModel`
        """
        model = IndexTrainingStatusResponseModel()
        if include_optional:
            return IndexTrainingStatusResponseModel(
                training_indexes = [
                    ''
                    ],
                retrain_threshold = 56,
                worker_pid = 56,
                global_training = { }
            )
        else:
            return IndexTrainingStatusResponseModel(
                training_indexes = [
                    ''
                    ],
                retrain_threshold = 56,
                worker_pid = 56,
                global_training = { },
        )
        """

    def testIndexTrainingStatusResponseModel(self):
        """Test IndexTrainingStatusResponseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
