name: Test CyborgDB Python SDK

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cyborgdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout SDK code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Checkout cyborgdb-service repository
        uses: actions/checkout@v4
        with:
          repository: cyborginc/cyborgdb-service
          ref: main
          path: cyborgdb-service
          token: ${{ secrets.CYBORGDB_SERVICE_TOKEN }}
          
      - name: Install cyborgdb-service from source
        run: |
          # Install the server from the cloned repository
          pip install ./cyborgdb-service
          
      - name: Install SDK dependencies
        run: |
          pip install -e .
          pip install pytest pytest-cov pytest-asyncio
          # Install optional test dependencies
          pip install langchain langchain-community
          
      - name: Set up environment
        run: |
          echo "CYBORGDB_API_KEY=${{ secrets.CYBORGDB_API_KEY }}" >> $GITHUB_ENV
          echo "CYBORGDB_DB_TYPE=postgres" >> $GITHUB_ENV
          echo "CYBORGDB_CONNECTION_STRING=host=localhost port=5432 dbname=cyborgdb user=postgres password=postgres" >> $GITHUB_ENV
          
      - name: Start CyborgDB service
        run: |
          # Start the service in the background using nohup to prevent it from blocking
          nohup cyborgdb-service > server.log 2>&1 &
          echo $! > server.pid
          # Wait for the service to be ready with a retry loop (max 30s)
          for i in {1..30}; do
            if curl -fs http://localhost:8000/v1/health > /dev/null; then
              echo "Service is up!"
              break
            fi
            sleep 1
          done
          # Final check, fail if not up
          if ! curl -fs http://localhost:8000/v1/health > /dev/null; then
            echo "Service failed to start after waiting 30 seconds"
            echo "Server logs:"
            cat server.log
            exit 1
          fi
          
      - name: Run tests
        run: |
          pytest tests/ -v --cov=cyborgdb --cov-report=term-missing
          
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
        continue-on-error: true